# Generated by Django 5.1.4 on 2025-02-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarketanalysis', '0002_alter_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(max_length=30),
        ),
    ]
